apiVersion: 1

groups:
  - orgId: 1
    name: midterm-app
    folder: Observability
    interval: 1m
    rules:
      - uid: high-error-rate
        title: HighErrorRate
        condition: C
        for: 1m
        noDataState: NoData
        execErrState: Error
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              refId: A
              expr: increase(app_errors_total[1m])
              instant: true
          - refId: B
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: __expr__
            model:
              refId: B
              type: reduce
              expression: A
              reducer: last
          - refId: C
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: __expr__
            model:
              refId: C
              type: threshold
              expression: B
              conditions:
                - evaluator:
                    params: [5]
                    type: gt
        labels:
          severity: critical
        annotations:
          summary: "CRITICAL: error rate exceeded 5 per minute"
